### ISSUE TITLE
Change a couple of signature definitions that have been modified

### ISSUE THREAD

**Issue by antaenc** [senzing-garage/sz-sdk-python-grpc#135]
find_network_by_entity_id and find_network_by_record_id:

- build_out_degree: int, -> build_out_degrees: int,
- flags: int = SzEngineFlags.SZ_FIND_PATH_DEFAULT_FLAGS, -> flags: int = SzEngineFlags.SZ_FIND_NETWORK_DEFAULT_FLAGS,

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/senzing-garage/sz-sdk-python-grpc/pull/139
- https://github.com/senzing-garage/sz-sdk-python-grpc/pull/145
